### ISSUE TITLE
Many embedded packages updated with latency due to push errors

### ISSUE THREAD

**Issue by mstick99** [chocolatey-community/chocolatey-coreteampackages#1217]
**Issue reused  and edited by @majkinetor since it was not filled**

---

Many larger embedded packages - which type is majority here - can and will fail to push to gallery until the upstream problem chocolatey/chocolatey.org#613 is fixed.

[Report sample](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/3d377aaa83e0012d9855c28aff1123ec08aed0b5#errors)

The error is:
```
Attempting to push <package_name>.nupkg to https://push.chocolatey.org 
There was an internal server error, which might mean the package already exists on a Simple OData Server.
```

Packages from this repo being afected at this time:

- calibre
- chromium
- cmake.portable
- docker-kitematic
- keeweb
- php
- python3
- sweet-home-3d
- waterfox

**Comment by AdmiringWorm** [comment]
We're aware of the new version of Waterfox. Unfortunately the following issue is preventing the update: https://github.com/chocolatey/chocolatey.org/issues/613

**Comment by majkinetor** [comment]
I reused this ticket since I realized that we currently have bunch of packages on errors and this will only go up, and almost never down based on my tests. Repeats and ignores on `updateall`  do not help at all.

At least for me, **this means the end of development and maintenance here or on any AU repo** until the problem is fixed upstream.

/cc @ferventcoder @gep13

**Comment by majkinetor** [comment]
So what is the status with this ? Does it still happen ? I didn't notice errors recently maybe, out of memory few times.

/cc @gep13 @AdmiringWorm @mkevenaar

**Comment by gep13** [comment]
@majkinetor the changes that were made to chocolatey.org have definitely helped the situation, but I am not going to say that everything has been fixed.  

Until we make changes to the actual physical infrastructure behind chocolatey.org there won't be much else that we can do though.

**Comment by majkinetor** [comment]
Its definite that problem isn't fixed based on AU reports since you introduced a change.
It occurs several times less then before and with different errors but still occurs in non-ignorable quantity.

**Comment by gep13** [comment]
@majkinetor there is still some infrastructure work pending for chocolatey.org that needs to be done before we can make anymore changes in this area.  I currently don't know when that work is due to be completed, but I will let you know as soon as I know.

**Comment by majkinetor** [comment]
I added '_package version already exists on the repository_' to my AU options in [repeat/ignore section](https://github.com/majkinetor/au-packages/blob/master/update_all.ps1#L37) and it [works](https://ci.appveyor.com/project/majkinetor/au-packages) in preventing errors which may be annoying as there is nothing we can do.

**Comment by majkinetor** [comment]
Bunch of packages still randomly fail. Only larger packages are prone to this and are currently ignored by AU. All will eventually  be published.

**Comment by cprivite** [comment]
Ok so what can we do to help fix this. Do you need help with a pull request or fixing some code? Do you need money for back end improvements? This is rediculous at this point. Like tell us what _actually_ needs to happen, regardless of if it's technical or political or what.

**Comment by ExE-Boss** [comment]
And&nbsp;once&nbsp;again “**qBittorrent**” [failed&nbsp;to&nbsp;be&nbsp;pushed](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/036ec8dd27492037c739afc3d5c8304c93e51d31#ignored):

> ## Ignored
>
>
> |Icon|Name|NuspecVersion|IgnoreMessage|
> |---|---|---|---|
> |<img src="https://cdn.jsdelivr.net/gh/chocolatey-community/chocolatey-coreteampackages@edba4a5849ff756e767cba86641bea97ff5721fe/icons/qbittorrent.png" width="32" height="32"/>|[qbittorrent](https://chocolatey.org/packages/qbittorrent/4.2.0)|[4.2.0](https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/qbittorrent)|AU ignored on: System.Management.Automation.RuntimeException: Chocolatey v0.10.15 Attempting to push qbittorrent.4.2.0.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository.|

**Comment by majkinetor** [comment]
There are litterrary hundreeds of packages failing.

**Comment by majkinetor** [comment]
This is literray almost 2 years not solved ...

**Comment by ferventcoder** [comment]
Howdy folks! Apologies that we've had trouble identifying and fixing this. A lot of the work we've done around this feels like whack-a-mole and I appreciate that you've stuck with us while we've continued to work to resolve these issues. 

That said, as mentioned over at https://github.com/chocolatey/chocolatey.org/issues/613, we've made some changes recently that may have went a long way into fixing the issues with pushing packages. Can I ask that if you see any issues with this, please comment on that issue so we can work to investigate them in near term?

**Comment by majkinetor** [comment]
I will close this as it doesn't seem to happen anymore.

**Comment by gep13** [comment]
@majkinetor thanks for following up with this! Do you know when the last time this happened from this repository was?

**Comment by majkinetor** [comment]
You could browse trhough history easily. Quickly searching it found many around month ago, for example [05-01](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/5e509fb3fef0a1c32732382c989e04e4f8b06777)

**Comment by AdmiringWorm** [comment]
@majkinetor the error in that report is for a different issue, which usually doesn't prevent the package from showing up on the website.

@gep13 the latest time the error seemed to happen was four days ago (the chromium package): https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/bf09e720bc20daea24728b2324d3b0bb3d3e57bb

**Comment by majkinetor** [comment]
Good catch @AdmiringWorm, seems I closed this prematurelly.

**Comment by gep13** [comment]
@majkinetor am I right in saying that you haven't seen any further instances of Out of Memory exceptions, or other errors, when pushing packages to chocolatey.org?

**Comment by majkinetor** [comment]
Yah, fix looks legit so far 👍

**Comment by gep13** [comment]
>@majkinetor said...
Yah, fix looks legit so far 👍

That is great news!
