### ISSUE TITLE
(python) Python3 32-bit (force_x86) non-existent registry path for "ErrorActionPreference"

### ISSUE THREAD

**Issue by arizvisa** [chocolatey-community/chocolatey-coreteampackages#1499]
When installing python3 with the `force_x86` option, an error is logged claiming that the `HKLM:\SOFTWARE\Python\PythonCore\3.7\InstallPath` key does not exist. This is because when installing the 32-bit version, the version key (`3.7`) is suffixed with `-32`. So the full key should actually be `HKLM:\SOFTWARE\Python\PythonCore\3.7-32\InstallPath`

Here is an excerpt from the terminal output:

```
python3 v3.7.7 [Approved]
python3 package files install completed. Performing other installation steps.
Installing 32-bit python3...
python3 has been installed.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'HKLM:\SOFTWARE\Python\PythonCore\3.7\InstallPath' because it does not exist.
  python3 can be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
The install of python3 was NOT successful.
Error while running 'C:\ProgramData\Chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
 See log for details.
```

I believe this issue is related to #1477, and is mentioned by another user in disqus at http://disq.us/p/28ht3aq.

## Expected Behavior
Although it doesn't seem that the error is critical or anything if you're installing to the default directory, the package needs to suffix the calculated registry key with `-32` when the x86 version is being installed.

As prior mentioned, the key should be `HKLM:\SOFTWARE\Python\PythonCore\3.7-32\InstallPath` (depending on which version is being installed of course)

## Current Behavior
As of now, the 3.7 installer assumes the registry key is at `HKLM:\SOFTWARE\Python\PythonCore\3.7\InstallPath` which doesn't exist.

## Possible Solution
The usage of the `$twoPartVersion` variable at [automatic/python3/tools/chocolateyInstall.ps1:34](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/a5835e4b4050651de131e058898d54dd966c42bd/automatic/python3/tools/chocolateyInstall.ps1#L34) should check if the 32-bit version of python is being installed in order to determine if the `-32` suffix needs to be included as part of the version. Maybe it'll be more defensive to check the existence of the key at multiple paths and then choose the one that exists(?).

The `$twoPartVersion` variable is first calculated here:
https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/a5835e4b4050651de131e058898d54dd966c42bd/automatic/python3/tools/chocolateyInstall.ps1#L6

The `$twoPartVersion` variable is used here:
https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/a5835e4b4050651de131e058898d54dd966c42bd/automatic/python3/tools/chocolateyInstall.ps1#L34

## Steps to Reproduce (for bugs)
1. Install a 32-bit version of Windows. There's a packer template available for Windows 8.1-x86 (that I used for reproing this) as part of the boxcutter/windows repository at https://github.com/boxcutter/windows/blob/master/eval-win81x86-enterprise.json
2. Bootstrap chocolatey
3. Install python3 with the `--forcex86` parameter.
4. When chocolatey runs the `chocolateyInstall.ps1` script, the aforementioned error will be logged.

## Context
I do not believe this affects me, but I believe it will affect users that try to install to a non-default Python path (some path other than `C:/Python37`) using the `--InstallDir` parameter. If any other dependent software tries to use the registry to locate the Python installation direcotry, they will be unable to locate it and Python will fall back to its alternative (weaker) methods in order to determine the library path.

## Your Environment
I'm using eval-win81-x86, but I don't believe the platform really matters.

**Comment by AdmiringWorm** [comment]
This issue have been resolved in the repository, and a package fix is in the process of being submitted to chocolatey.org for version 3.8.x (fix versions for older versions and beta versions are not planned at this time).

**Comment by layanto** [comment]
I still have this problem without forcing 32-bit. I am on Python 3.8.4 (installed with chocolatey), upgrading to 3.9.0 raised the error that registry key InstallPath not found even though the registry key is there. In fact, Python 3.9 successfully installed in c:\Python39 but c:\Python38 was not uninstalled.

![image](https://user-images.githubusercontent.com/245078/95266870-cbeb5b00-087f-11eb-84c5-624b60fad456.png)

![image](https://user-images.githubusercontent.com/245078/95266911-e02f5800-087f-11eb-807c-ed20661d2d58.png)
